- name: Updating /etc/hosts
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1  localhost
      127.0.1.1  codetest
      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

- name: Assigning new hostname
  hostname: name=codetest
- name: reset ssh connection to allow user changes to affect new hostname
  meta: reset_connection

- name: Changing the timezone
  copy:
    dest: /etc/timezone
    content: "America/New_York"

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
- name: reset ssh connection to allow timezone changes to affect ubuntu current login user
  meta: reset_connection

#- name: set timezone to America/New_York
#  timezone:
#    name: America/New_York