---
pkg_reqs:
  # server software
  - wget
  # Install packages to allow apt to use a repository over HTTPS
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  # python
  - python-pip
